 - name: Install base required packages
   yum: name={{ item }} state=present
   with_items:
       - vim
       - wget
       - screen
       - sudo

 - name: Install Development tools
   yum: name="@Development tools" state=present
       
