- name: Unpack {{ pkg }}
  unarchive:
    src: "{{ lfs_src }}/{{ pkg }}"
    dest: "{{ lfs_src }}"
    copy: no

- name: Create build directory
  file:
    path: "{{ lfs_src }}/{{ pkg_dir }}/build"
    state: directory

- name: Run Configure
  command: ../configure --prefix=/tools --with-sysroot=$LFS --with-lib-path=/tools/lib --target=$LFS_TGT --disable-nls --disable-werror
  args: 
    chdir: "{{ lfs_src }}/{{ pkg_dir }}/build"

#- name: Make
#  command: make chdir="{{ lfs_src }}/{{ pkg_dir }}/build"

- name: Make
  make:
    chdir="{{ lfs_src }}/{{ pkg_dir }}/build"

- name: create /tool/lib symlink
  script: liblink.sh
    
#- name: Make install
#  command: make install chdir="{{ lfs_src }}/{{ pkg_dir }}/build"
- name: Make Install
  make:
    chdir: "{{ lfs_src }}/{{ pkg_dir }}/build"
    target: install
    
- name: Delete build directory {{ lfs_src }}/{{ pkg_dir }}
  file:
    path: "{{ lfs_src }}/{{ pkg_dir }}"
    state: absent